name: Deploy ARM Template

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: 0edc3c13-e0f0-480d-9341-0aeb587cc1c3
        resourceGroupName: GitHubActionExercise-rg
        template: ./azuredeploy.json
